### PR TITLE
Updating OpenML blog header

### PR DESCRIPTION
**Pull request by Neeratyoy**
Fixing/updating #8.

### CODE REVIEW

**Comment by Neeratyoy** [comment]
Hi @prabhant 

I followed the structure present in the other existing notebook on OpenML and DL.
PFA the screenshot of the head of the notebook is rendered on jupyter.

Screenshot from 2020-06-10 16-58-07

Kindly let me know if this fits the expectation.

Thanks!

**Comment by prabhant** [comment]
Can you make the following changes:

1. Delete one of the 'categories', you defined them twice
2. Change the Image directory from `./my_icons/openml.png,` to `images/fastpages_posts/`

**Comment by Neeratyoy** [comment]
> 2. Change the Image directory from `./my_icons/openml.png,` to `images/fastpages_posts/`

Should I also remap the image src in the notebook cell where the image is being rendered to this folder?
Currently, it uses the local/relative folder of `my_icons`.

**Comment by prabhant** [comment]
lgtm now :). I'll let you know after deployment if it requires any more changes.

**Pull request merged**
